# Generated by Django 5.1.7 on 2025-03-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_note_author_note_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
