# Generated by Django 5.1.7 on 2025-03-16 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_websiteuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='note',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_name',
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
