# Generated by Django 5.1.7 on 2025-04-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_status_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favourite',
        ),
    ]
