# Generated by Django 5.1.7 on 2025-03-23 13:51

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_note_date_of_birth_remove_note_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='password',
            field=models.CharField(max_length=128, validators=[api.models.validate_strong_password]),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genres', models.JSONField()),
                ('language', models.CharField(max_length=50)),
                ('mature', models.BooleanField(default=False)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
